name: Manual Release to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.0.0)'
        required: true
  push:
    tags:
      - "*.*.*"


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Update version, tag, and commit
        run: |          
          poetry version patch
          NEW_VERSION=$(poetry version -s)
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add pyproject.toml
          git commit -m "Update version to $NEW_VERSION"
          git push origin HEAD:main

      - name: prepare twine
        run: |
          rm -rf dist
          pip3 install twine

      - name: Publish package to PyPI
        run: |
          poetry build
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}

      - name: Finish
        run: echo "Package version $VERSION published to PyPI successfully"
