name: Manual Release to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: prepare twine
        run: |
          rm -rf dist
          pip3 install twine

      - name: Publish package to PyPI
        run: |
          poetry build
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}

      - name: Finish
        run: echo "Package version $VERSION published to PyPI successfully"
